### ISSUE TITLE
Masterlist of TODO's 

### ISSUE THREAD

**Issue by faye-tan** [uoftblueprint/the-period-purse#113]
Urgent:
- [ ] Problem with Log Multiple Days...in multiple years? what if we logged in 2020, 2021, and 2022? 
- [ ] Changes so that flow is mandatory and cannot be deselected
- [ ] Alignment/overlapping issues as found in https://docs.google.com/document/d/1EQPRgtxN-M9OdGmEhBanS5Ydr6JIwkkaiqEU_gkAPes/edit?usp=sharing
- [x] #104 -> assigned 04/02/2022
- [x] #85 -> assigned 04/14/2022
- [x] #103 
- [ ] iCloud backup user flow
  - [x] #121
- [x] #136
- [x] #125
<img width="769" alt="Screen Shot 2022-04-03 at 3 39 53 PM" src="https://user-images.githubusercontent.com/35851484/161445161-40573f79-ecbc-4bc0-a2cd-2fbdd94505d9.png">

- [ ] user can go back 1 year from date of onboarding 
- [x] #122 
- [x] #123
- [ ] Lazy loaders, especially needed on cycle page
- [x] #135

Not urgent: 
- [x] #88 
- [x] #115  -> assigned 04/02/2022
- [x] log symptoms/log multiple symptoms bug on #110  ?? It's not happening on Emily's branch
- [x] #116  -> assigned 04/02/2022
- [x] #118  -> assigned 04/02/2022
- [x] #119
- [x] #120  -> assigned 04/02/2022
- [ ] #117  -> assigned 04/02/2022
- [x] #124
- [x] When opening filter selection, calendar should be stationary and not move
- [ ] Software License

Nice to have: 
- [x] Save button only enabled when changes are made to Log Symptoms screen
- [ ] Performance? 
- [ ] Clean up README -> Some of it belongs in WIKI
- [ ] Save button on log multiple dates enabled only when changes made

Notes from Jana: 
- making bar teal 
- tap anywhere to close on confirmation 
- period at end of tap to learn more about period products 
- Period underwear no S 
- Cups not plural 
- Period after purse and all instead of comma on Footer 
- Privacy Policy both capital inside of page
- Any questions? plural 
- Privacy policy no period at end of footer
-  Terms and Conditions capitalized inside of page 
- Privacy policy no period on onboarding 
- By default
- screen recording for video

**Comment by jingxcode** [comment]
<img width="375" alt="welcome-1" src="https://user-images.githubusercontent.com/91763418/163467002-651e798f-2651-4aa7-9c89-79eae957cea2.png">

Add "By continuing you accept the Terms and Conditions and Privacy Policy." on welcome page

**Comment by faye-tan** [comment]
^ Added as part of #115
